[relaychain.genesis.runtimeGenesis.patch.configuration.config.async_backing_params]
  max_candidate_depth = 6
  allowed_ancestry_len = 2

[relaychain.genesis.runtimeGenesis.patch.configuration.config.scheduler_params]
  max_validators_per_core = 1
  num_cores = 2
  lookahead = 3

[relaychain]
default_command = "polkadot"
chain = "rococo-local"

  [[relaychain.node_groups]]
  name = "elastic-validator"
  count = 3

[[parachains]]
id = 1000
chain_spec_path = "./dev_chain_spec.json"

[parachains.collator]
name = "charlie"
ws_port = 9988
command = "polkadot-omni-node"
args = [ "--experimental-use-slot-based", "-lparachain::collation-generation=trace,parachain::collator-protocol=trace,parachain=debug,cumulus-collator=trace,aura=trace" ]
